### ISSUE TITLE
Kernel Panic - blocking while holding a spinlock

### ISSUE THREAD

**Issue by C44Supra** [vit9696/AppleALC#96]
I have only just updated to 10.12.1 and I'm having some issues with AppleALC.

Initially the system boots and panics in the early "Apple logo loading screen"

![img_0614](https://cloud.githubusercontent.com/assets/9249490/19721379/4314441e-9b72-11e6-9df2-2dc25b77cc84.JPG)

 with the message:

`thread_invoke: preemption_level 1, possible cause: blocking while holding a spinlock, or within int...`

I have no idea what comes after int... because it reboots stupidly fast, then tells me there was a problem booting and continues to boot normally, like nothing ever happened.

I am still running 1.0.16 but didn't see anything in your 1.0.17 that indicates the issue might be solved already. The motherboard I'm using is a Asus Z170 Pro Gaming, which I believe has a the ALC1150 audio chipset.

**Comment by vandroiy2013** [comment]
Update to AppleALC 1.0.17

**Comment by C44Supra** [comment]
Just did, no difference. Same exact problem as with 1.0.16 just that the kext in the backtrace now reads version 1.0.17. I did manage to get a shot of the entire screen this time around.

![img_0616](https://cloud.githubusercontent.com/assets/9249490/19722445/097c0674-9b77-11e6-8af0-8ae0781a828e.JPG)

The entire first line reads:
`thread_invoke: preemption_level 1, possible cause: blocking while holding a spinlock, or within interrupt context  "@/Library/Caches/com.apple.xbs/Sources/xnu/xnu-3789.21.3/osfmk/kern/sched_prim.c:2207"`

I did however run Kextutility to rebuild the caches so I'm thinking that shouldn't be it.

**Comment by vandroiy2013** [comment]
debux=0x100 and keepsyms=1 in boot args.

**Comment by C44Supra** [comment]
I just ran it with "debux" (I figured it was a typo but tried it anyways). What exactly does keepsyms=1 do?

**Comment by C44Supra** [comment]
Extremely weird. I ran "debux" + keepsyms and didn't get a panic. Then, after you edited your reply, I ran debug + keepsyms. No panic. Took both arguments out... no panic. Cold started it, no panic. Restarted it again... no panic.

Am I wrong in the assumption that debug and keepsyms are merely for diagnostic purposes in that they echo a few more hints as to what (part) is actually causing a panic?

**Comment by vandroiy2013** [comment]
Yes. They are only for diagnostic purposes. Maybe broken kernel cache causing a panic... If it happens again add keepsyms=1 in bootargs and provide a panic log. If your NVRAM is working you can boot with -alcoff then and get full log after booting into desktop.

**Comment by vit9696** [comment]
I think the issue might actually exist, although I am not certain what exactly happens.
Please catch the panic with keepsyms=1 enabled, and provide a full panic log.
This way we might be able to help you.

I think this is better to reopen the issue, since even if it is hard to reproduce and rare to run into, it is likely valid for now.

**Comment by C44Supra** [comment]
I shall keep it in there and reboot as often as I can in hope of catching it again. 

@vandroiy2013 I assume -alcoff basically disables this kext? I can boot into Sierra but the issue is that it doesn't always do it straightaway. For instance, initially when I booted or rebooted it threw this panic and then rebooted itself in seconds. Then it booted and while booting showed me a screen that reminds me of the earlier more graphical kernel panics, but now it says something along the lines of "there was a problem during your previous boot and the system will now boot normally" and then you have the option of waiting a few seconds or pressing a key after which it'll boot into Sierra no problem, even the audio works just fine.

**Comment by vandroiy2013** [comment]
With working NVRAM after panic use -alcoff, boot into OS and you'll see splash screen with panic report. Choose Detailed (or something similar) and you'll get detailed panic report... Copy/paste it here...

**Comment by C44Supra** [comment]
Gotcha. I think I'll put that into the bootargs, just in case. I just rebooted but nothing came up, I'm guessing that the several cold and hot restarts might have something to do with that.

**Comment by vit9696** [comment]
The issue should be resolved with the recent commit. Please reopen if it still causes you bugs.

**Comment by C44Supra** [comment]
Not resolved, but certainly less frequent. This one popped up just yesterday:
![img_0719](https://cloud.githubusercontent.com/assets/9249490/20793948/dae3e5ba-b7c9-11e6-94ad-258a423b0efd.JPG)

No log or anything once rebooted into OSX though.

**Comment by vandroiy2013** [comment]
@C44Supra, Your AppleALC.kext is 1.0.17, latest kext should be 1.0.18

**Comment by C44Supra** [comment]
@vandroiy2013 Looking at the releases page I only see 1.0.17?

**Comment by vandroiy2013** [comment]
@C44Supra, You have to build new version from latest sources...

**Comment by vandroiy2013** [comment]
@C44Supra, Here is 1.0.18 Debug with latest commit
[AppleALC.kext.zip](https://github.com/vit9696/AppleALC/files/624583/AppleALC.kext.zip)

**Comment by C44Supra** [comment]
Got it, installed it just now. Will report back.
